/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiError
 */
export interface ApiError {
    /**
     * 
     * @type {number}
     * @memberof ApiError
     */
    errorCode?: ApiErrorErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiError
     */
    errorMessage?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ApiErrorErrorCodeEnum {
    NUMBER_400 = 400,
    NUMBER_401 = 401,
    NUMBER_500 = 500
}



