/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Profile } from './profile';

/**
 * 
 * @export
 * @interface CreateProfilesResponse
 */
export interface CreateProfilesResponse {
    /**
     * List of created profile ids
     * @type {Array<string>}
     * @memberof CreateProfilesResponse
     */
    profileIDs?: Array<string>;
    /**
     * List of profiles that were NOT created
     * @type {Array<Profile>}
     * @memberof CreateProfilesResponse
     */
    invalid?: Array<Profile>;
}


