/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Finding } from './finding';
import { Measurements } from './measurements';

/**
 * 
 * @export
 * @interface EcgMetaData
 */
export interface EcgMetaData {
    /**
     * The unique identifier of an ECG
     * @type {string}
     * @memberof EcgMetaData
     */
    ecgId?: string;
    /**
     * The date/time of the ECG
     * @type {string}
     * @memberof EcgMetaData
     */
    ecgDateTime?: string;
    /**
     * The request context of the ECG
     * @type {string}
     * @memberof EcgMetaData
     */
    requestContext?: string;
    /**
     * The list of custom findings of the ECG
     * @type {Array<Finding>}
     * @memberof EcgMetaData
     */
    findings?: Array<Finding>;
    /**
     * Indicates whether the ECG measurements are confiremed or not
     * @type {boolean}
     * @memberof EcgMetaData
     */
    isConfirmedMeasurements?: boolean;
    /**
     * 
     * @type {Measurements}
     * @memberof EcgMetaData
     */
    measurements?: Measurements;
}


