/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EcgComment } from './ecg-comment';
import { EcgFinding } from './ecg-finding';
import { EcgInterpretation } from './ecg-interpretation';
import { EcgLeads } from './ecg-leads';
import { EcgMeasurements } from './ecg-measurements';
import { ElectrodesStatus } from './electrodes-status';
import { Symptom } from './symptom';

/**
 * 
 * @export
 * @interface EcgData
 */
export interface EcgData {
    /**
     * The ECG Feedback text. Relevant for non-professional users and in case the ECG is   completely not readable.
     * @type {string}
     * @memberof EcgData
     */
    recommendations?: string;
    /**
     * The severity of the ECG Recommendation (Feedback). Relevant for non-professional users   and in case the ECG is completely not readable.  Possible values are:    (-1) - The ECG is not readable;    1 - \"green\" severity;   2 - \"yellow\" severity;   3 - \"organe\" severity;   4 - \"red\" severity
     * @type {number}
     * @memberof EcgData
     */
    severity?: number;
    /**
     * The current status of the ECG transmission.   Possible values are:   0 - The ECG is not readable;   1 - The ECG is only partly ready. Relevant when the user has interpretation service and it was not given yet, but    the ECG graph is already available.   2 - The ECG is ready.
     * @type {number}
     * @memberof EcgData
     */
    status?: number;
    /**
     * The remarks the user has entered during the ECG transmission process.
     * @type {string}
     * @memberof EcgData
     */
    remarks?: string;
    /**
     * Technical instructions to improve the ECG quality. Given automatically based on the ECG quality and MC input.
     * @type {string}
     * @memberof EcgData
     */
    technicalInstructions?: string;
    /**
     * 
     * @type {ElectrodesStatus}
     * @memberof EcgData
     */
    electrodesStatus?: ElectrodesStatus;
    /**
     * 
     * @type {EcgMeasurements}
     * @memberof EcgData
     */
    measurements?: EcgMeasurements;
    /**
     * The list of ECG findings, with their respective categories. Relevant for professional users with service only.
     * @type {Array<EcgFinding>}
     * @memberof EcgData
     */
    findings?: Array<EcgFinding>;
    /**
     * The symptos the user has selected during the ECG transmissionn process.
     * @type {Array<Symptom>}
     * @memberof EcgData
     */
    symptoms?: Array<Symptom>;
    /**
     * 
     * @type {EcgLeads}
     * @memberof EcgData
     */
    leads?: EcgLeads;
    /**
     * 
     * @type {Array<EcgComment>}
     * @memberof EcgData
     */
    comments?: Array<EcgComment>;
    /**
     * 
     * @type {EcgInterpretation}
     * @memberof EcgData
     */
    interpretation?: EcgInterpretation;
}


