/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EcgInterpretation
 */
export interface EcgInterpretation {
    /**
     * The name of the interpreter who wrote the interpretation
     * @type {string}
     * @memberof EcgInterpretation
     */
    interpreter?: string;
    /**
     * The interpretation text
     * @type {string}
     * @memberof EcgInterpretation
     */
    text?: string;
    /**
     * The interpretation (local) date/time
     * @type {string}
     * @memberof EcgInterpretation
     */
    interpretationDate?: string;
    /**
     * Indicates whether to send an email notification about the interpretation to the user or not
     * @type {boolean}
     * @memberof EcgInterpretation
     */
    notifyUser?: boolean;
}


