/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EcgFinding
 */
export interface EcgFinding {
    /**
     * The Category of the finding
     * @type {string}
     * @memberof EcgFinding
     */
    category?: string;
    /**
     * The name of the finding
     * @type {string}
     * @memberof EcgFinding
     */
    finding?: string;
}


