/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EcgLeads
 */
export interface EcgLeads {
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    rhythm?: string;
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    l1?: string;
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    l2?: string;
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    l3?: string;
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    avr?: string;
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    avl?: string;
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    avf?: string;
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    v1?: string;
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    v2?: string;
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    v3?: string;
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    v4?: string;
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    v5?: string;
    /**
     * 
     * @type {string}
     * @memberof EcgLeads
     */
    v6?: string;
}


