/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Finding
 */
export interface Finding {
    /**
     * 
     * @type {string}
     * @memberof Finding
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Finding
     */
    value?: string;
}


