/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Measurements
 */
export interface Measurements {
    /**
     * The rate (pulse) ECG measurement
     * @type {string}
     * @memberof Measurements
     */
    rate?: string;
    /**
     * The PR ECG measurement
     * @type {string}
     * @memberof Measurements
     */
    pr?: string;
    /**
     * The Qrs ECG measurement
     * @type {string}
     * @memberof Measurements
     */
    qrs?: string;
    /**
     * The QT ECG measurement
     * @type {string}
     * @memberof Measurements
     */
    qt?: string;
    /**
     * The QTcB ECG measurement
     * @type {string}
     * @memberof Measurements
     */
    qtcb?: string;
    /**
     * The QTcF ECG measurement
     * @type {string}
     * @memberof Measurements
     */
    qtcf?: string;
}


