/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PortalProfile } from './portal-profile';

/**
 * 
 * @export
 * @interface PortalPermission
 */
export interface PortalPermission {
    /**
     * The unique user id of the user
     * @type {string}
     * @memberof PortalPermission
     */
    userId?: string;
    /**
     * The first name of the user
     * @type {string}
     * @memberof PortalPermission
     */
    firstName?: string;
    /**
     * The last name of the user
     * @type {string}
     * @memberof PortalPermission
     */
    lastName?: string;
    /**
     * The date and time of the last ECG the user has done
     * @type {string}
     * @memberof PortalPermission
     */
    lastEcgDate?: string;
    /**
     * The number of the user\'s unviewed interpretation in the portal
     * @type {number}
     * @memberof PortalPermission
     */
    unviewedInterpretations?: number;
    /**
     * The number of the user\'s unviewed ECGs in the portal
     * @type {number}
     * @memberof PortalPermission
     */
    unviewedEcgsInPortal?: number;
    /**
     * The list of profiles of the user
     * @type {Array<PortalProfile>}
     * @memberof PortalPermission
     */
    profiles?: Array<PortalProfile>;
}


