/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProfileEcg
 */
export interface ProfileEcg {
    /**
     * The unique identifier of the ECG
     * @type {string}
     * @memberof ProfileEcg
     */
    ecgId?: string;
    /**
     * The ECG date and time
     * @type {string}
     * @memberof ProfileEcg
     */
    ecgDateTime?: string;
}


