/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiError } from './api-error';
import { EcgMetaData } from './ecg-meta-data';

/**
 * 
 * @export
 * @interface ShApiResponseEcgMetaData
 */
export interface ShApiResponseEcgMetaData {
    /**
     * 
     * @type {ApiError}
     * @memberof ShApiResponseEcgMetaData
     */
    error?: ApiError;
    /**
     * 
     * @type {EcgMetaData}
     * @memberof ShApiResponseEcgMetaData
     */
    response?: EcgMetaData;
}


