/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiError } from './api-error';
import { CreateProfilesResponse } from './create-profiles-response';

/**
 * 
 * @export
 * @interface ShApiResponseCreateProfilesResponse
 */
export interface ShApiResponseCreateProfilesResponse {
    /**
     * 
     * @type {ApiError}
     * @memberof ShApiResponseCreateProfilesResponse
     */
    error?: ApiError;
    /**
     * 
     * @type {CreateProfilesResponse}
     * @memberof ShApiResponseCreateProfilesResponse
     */
    response?: CreateProfilesResponse;
}


