/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IProfile } from './iprofile';

/**
 * 
 * @export
 * @interface ICreateProfilesResponse
 */
export interface ICreateProfilesResponse {
    /**
     * List of created profile ids
     * @type {Array<string>}
     * @memberof ICreateProfilesResponse
     */
    profileIDs?: Array<string>;
    /**
     * List of profiles that were NOT created
     * @type {Array<IProfile>}
     * @memberof ICreateProfilesResponse
     */
    invalid?: Array<IProfile>;
}


