/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IOrganization } from './iorganization';

/**
 * 
 * @export
 * @interface IEcg
 */
export interface IEcg {
    /**
     * The ECG user unique identifier
     * @type {string}
     * @memberof IEcg
     */
    userId?: string;
    /**
     * The ECG user first bane
     * @type {string}
     * @memberof IEcg
     */
    firstName?: string;
    /**
     * The ECG user last name
     * @type {string}
     * @memberof IEcg
     */
    lastName?: string;
    /**
     * 
     * @type {IOrganization}
     * @memberof IEcg
     */
    organization?: IOrganization;
    /**
     * The ECG profile unique identifier
     * @type {string}
     * @memberof IEcg
     */
    profileId?: string;
    /**
     * The ECG profile first name
     * @type {string}
     * @memberof IEcg
     */
    profileFirstName?: string;
    /**
     * The ECG profile last name
     * @type {string}
     * @memberof IEcg
     */
    profileLastName?: string;
    /**
     * The ECG unique identifier
     * @type {string}
     * @memberof IEcg
     */
    ecgId?: string;
    /**
     * The ECG date/time
     * @type {string}
     * @memberof IEcg
     */
    ecgDateTime?: string;
    /**
     * Indicates whether the ECG is yet unviewed in the portal
     * @type {boolean}
     * @memberof IEcg
     */
    unviewedInPortal?: boolean;
    /**
     * Indicates whether the ECG interpretation is yet unviewed in the portal
     * @type {boolean}
     * @memberof IEcg
     */
    interpretationUnviewedInPortal?: boolean;
}


