/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IEcgComment
 */
export interface IEcgComment {
    /**
     * The text of the comment
     * @type {string}
     * @memberof IEcgComment
     */
    text?: string;
    /**
     * The comment date and time
     * @type {string}
     * @memberof IEcgComment
     */
    commentDate?: string;
    /**
     * The name of the commenter
     * @type {string}
     * @memberof IEcgComment
     */
    commenter?: string;
}


