/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IEcgMeasurements
 */
export interface IEcgMeasurements {
    /**
     * Indicates whether the measurements are unconfirmed (automatic) or not
     * @type {boolean}
     * @memberof IEcgMeasurements
     */
    isUnconfirmed?: boolean;
    /**
     * Indicates whether the measurements values units are in ms (or seconds).   Note: The Rate (pulse) measurement is always in bpm
     * @type {boolean}
     * @memberof IEcgMeasurements
     */
    isMs?: boolean;
    /**
     * The rate (pulse) ECG measurement
     * @type {string}
     * @memberof IEcgMeasurements
     */
    rate?: string;
    /**
     * The PR ECG measurement
     * @type {string}
     * @memberof IEcgMeasurements
     */
    pr?: string;
    /**
     * The Qrs ECG measurement
     * @type {string}
     * @memberof IEcgMeasurements
     */
    qrs?: string;
    /**
     * The QT ECG measurement
     * @type {string}
     * @memberof IEcgMeasurements
     */
    qt?: string;
    /**
     * The QTcB ECG measurement
     * @type {string}
     * @memberof IEcgMeasurements
     */
    qtcb?: string;
    /**
     * The QTcF ECG measurement
     * @type {string}
     * @memberof IEcgMeasurements
     */
    qtcf?: string;
}


