/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IFinding } from './ifinding';
import { IMeasurements } from './imeasurements';

/**
 * 
 * @export
 * @interface IEcgMetaData
 */
export interface IEcgMetaData {
    /**
     * The unique identifier of an ECG
     * @type {string}
     * @memberof IEcgMetaData
     */
    ecgId?: string;
    /**
     * The date/time of the ECG
     * @type {string}
     * @memberof IEcgMetaData
     */
    ecgDateTime?: string;
    /**
     * The request context of the ECG
     * @type {string}
     * @memberof IEcgMetaData
     */
    requestContext?: string;
    /**
     * The list of custom findings of the ECG
     * @type {Array<IFinding>}
     * @memberof IEcgMetaData
     */
    findings?: Array<IFinding>;
    /**
     * Indicates whether the ECG measurements are confiremed or not
     * @type {boolean}
     * @memberof IEcgMetaData
     */
    isConfirmedMeasurements?: boolean;
    /**
     * 
     * @type {IMeasurements}
     * @memberof IEcgMetaData
     */
    measurements?: IMeasurements;
}


