/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IElectrodesStatus
 */
export interface IElectrodesStatus {
    /**
     * 
     * @type {boolean}
     * @memberof IElectrodesStatus
     */
    ll?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IElectrodesStatus
     */
    la?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IElectrodesStatus
     */
    ra?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IElectrodesStatus
     */
    v1?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IElectrodesStatus
     */
    v2?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IElectrodesStatus
     */
    v3?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IElectrodesStatus
     */
    v4?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IElectrodesStatus
     */
    v5?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IElectrodesStatus
     */
    v6?: boolean;
}


