/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Reperesents and organization which groups together differet users
 * @export
 * @interface IOrganization
 */
export interface IOrganization {
    /**
     * Thd unique identifier of the organization
     * @type {number}
     * @memberof IOrganization
     */
    organizationId?: number;
    /**
     * The display name of the organization
     * @type {string}
     * @memberof IOrganization
     */
    organizationName?: string;
}


