/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IApiError } from './iapi-error';
import { IFullSmartheartUser } from './ifull-smartheart-user';

/**
 * 
 * @export
 * @interface IShApiResponseFullSmartheartUser
 */
export interface IShApiResponseFullSmartheartUser {
    /**
     * 
     * @type {IApiError}
     * @memberof IShApiResponseFullSmartheartUser
     */
    error?: IApiError;
    /**
     * 
     * @type {IFullSmartheartUser}
     * @memberof IShApiResponseFullSmartheartUser
     */
    response?: IFullSmartheartUser;
}


