/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ISymptom
 */
export interface ISymptom {
    /**
     * The unique id of the symptom
     * @type {string}
     * @memberof ISymptom
     */
    symptomsId?: string;
    /**
     * The descriptive name of the symptom
     * @type {string}
     * @memberof ISymptom
     */
    symptomName?: string;
}


