/* tslint:disable */
/* eslint-disable */
/**
 * Smartheart Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IUserActivationData
 */
export interface IUserActivationData {
    /**
     * The activation token of the user to be activated
     * @type {string}
     * @memberof IUserActivationData
     */
    activationToken?: string;
    /**
     * The password to be set for the activated user
     * @type {string}
     * @memberof IUserActivationData
     */
    password?: string;
}


